spring.application.name=LoanManagementAppApplication

# Local DB
spring.datasource.url=jdbc:mysql://localhost:3306/loan_management_app
spring.datasource.username=root
spring.datasource.password=database

# Database (RDS)
# spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&verifyServerCertificate=false&serverTimezone=UTC
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Lambda Optimization
spring.main.web-application-type=servlet
spring.main.lazy-initialization=true

# JWT
jwt.secret=${JWT_SECRET:yourSuperSecretKeyForJwtGeneration123456}
jwt.expiration=86400000

# AWS
aws.accessKey=${My_AWS_ACCESS_KEY}
aws.secretKey=${My_AWS_SECRET_KEY}
aws.region=${My_AWS_REGION}
aws.bucketName=${My_AWS_BUCKET_NAME}