spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/loan_management_app
spring.datasource.username=root
spring.datasource.password=database
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=yourSuperSecretKeyForJwtGeneration123456
jwt.expiration=86400000

# AWS Credentials
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucketName=loan-doc-storage